### ISSUE TITLE
Fatal Error Isotope 2.1.13 / Contao 3.2.20 PHP 5.5 all-inkl.com MySQLi

### ISSUE THREAD

**Issue by anjuis** [hb-agency/contao_isotope_payment_paypal_proex#1]
Fatal error: Uncaught exception HttpException with message HttpRequest::__construct() expects at most 3 parameters, 4 given thrown in system/modules/isotope_payment_paypal_proex/library/Isotope/Model/Payment/PayPalExpress.php on line 330
#0 system/modules/isotope_payment_paypal_proex/library/Isotope/Model/Payment/PayPalExpress.php(330): HttpRequest->__construct('api-3t.paypal.c...', '/nvp', 'POST', true)
#1 system/modules/isotope_payment_paypal_proex/library/Isotope/Model/Payment/PayPalExpress.php(287): Isotope\Model\Payment\PayPalExpress->response('L_PAYMENTREQUES...')
#2 system/modules/isotope_payment_paypal_proex/library/Isotope/Model/Payment/PayPalExpress.php(275): Isotope\Model\Payment\PayPalExpress->doExpressCheckout(Array)
#3 system/modules/isotope/library/Isotope/Module/Checkout.php(184): Isotope\Model\Payment\PayPalExpress->checkoutForm(Object(Isotope\Model\ProductCollection\Order), Object(Isotope\Module\Checkout))
#4 system/modules/core/modules/Module.php(139): Isotope\Module\Checkout->compile()
#5 system/modules/isotope/library/Isotope/Module/Module.php(83): Contao\Module->generate()
#6 system/modules/isotope/library/Isotope/Module/Checkout.php(91): Isotope\Module\Module->generate()
#7 system/modules/core/elements/ContentModule.php(54): Isotope\Module\Checkout->generate()
#8 system/modules/core/library/Contao/Controller.php(457): Contao\ContentModule->generate()
#9 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#10 system/modules/core/modules/Module.php(139): Contao\ModuleArticle->compile()
#11 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
#12 system/modules/core/library/Contao/Controller.php(393): Contao\ModuleArticle->generate(false)
#13 system/modules/core/library/Contao/Controller.php(255): Contao\Controller->getArticle(Object(Contao\ArticleModel), false, false, 'main')
#14 system/modules/core/pages/PageRegular.php(129): Contao\Controller->getFrontendModule('0', 'main')
#15 index.php(254): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#16 index.php(443): Index->run()
#17 {main}

**Comment by anjuis** [comment]
Is there anything to know for using this extension with this version of isotope? Or is this a bug? Thanks
